<a href="https://colab.research.google.com/github/SahilBhragudev/Machine-Learning-Projects-Models/blob/machineLearning/Fake_News_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Import the Dependencies
import pandas as pd
import numpy as np
import re #regular expression used for searching words
from nltk.corpus import stopwords # natural language tool kit used to search stop words
from nltk.stem.porter import PorterStemmer # Gives the root word for a particular word
from sklearn.feature_extraction.text import TfidfVectorizer # Used to convert the text into feature
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [9]:
# Printing the stopwords in English
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

Data Pre processing

In [11]:
# Loading the dataset to pandas dataframe
news_dataset = pd.read_csv('/content/FA-KES-Dataset.csv',encoding='latin1')

In [13]:
news_dataset.shape

(804, 7)

In [14]:
news_dataset.head()

      unit_id  ... labels
0  1914947530  ...      0
1  1914947532  ...      0
2  1914947533  ...      0
3  1914947534  ...      0
4  1914947535  ...      0

[5 rows x 7 columns]

In [15]:
# check if some values are missing in the datset
news_dataset.isnull().sum()

unit_id            0
article_title      0
article_content    0
source             0
date               0
location           0
labels             0
dtype: int64

In [17]:
# Separting data and label
X = news_dataset.drop(columns='labels',axis = 1)
Y = news_dataset['labels']

In [18]:
print(X)
print(Y)

        unit_id  ...    location
0    1914947530  ...       idlib
1    1914947532  ...        homs
2    1914947533  ...      aleppo
3    1914947534  ...      aleppo
4    1914947535  ...      aleppo
..          ...  ...         ...
799  1965511221  ...      aleppo
800  1965511222  ...      aleppo
801  1965511224  ...      aleppo
802  1965511226  ...       idlib
803  1965511231  ...  deir ezzor

[804 rows x 6 columns]
0      0
1      0
2      0
3      0
4      0
      ..
799    1
800    1
801    0
802    1
803    1
Name: labels, Length: 804, dtype: int64

In [26]:
news_dataset['content'] = news_dataset['article_content'] + ' ' + news_dataset['location']

In [27]:
print(news_dataset['content'])

0      Wed 05 Apr 2017 Syria attack symptoms consiste...
1      Fri 07 Apr 2017 at 0914 Homs governor says U.S...
2      Sun 16 Apr 2017 Death toll from Aleppo bomb at...
3      Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...
4      Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...
                             ...
799    28-08-2016 Turkish Bombardment Kills 20 Civili...
800    17-08-2016 Martyrs as Terrorists Shell Aleppos...
801    03-08-2016 Chemical Attack Kills Five Syrians ...
802    01-08-2016 5 Killed as Russian Military Choppe...
803    April 6 2017 Syrian Army Kills 48 ISIL Terrori...
Name: content, Length: 804, dtype: object

Stemming

In [19]:
# Stemming is the process of reducing a word to it's root word
# Eg : actor , acting , actress -----> root word is 'act'

port_stem = PorterStemmer()

In [30]:
def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z],','',content)
  stemmed_content = stemmed_content.lower()
  stemmed_content = stemmed_content.split()
  stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content = ' '.join(stemmed_content)
  return stemmed_content

In [31]:
news_dataset['content'] = news_dataset['content'].apply(stemming)

In [32]:
print(news_dataset['content'])

0      wed 05 apr 2017 syria attack symptom consist n...
1      fri 07 apr 2017 0914 hom governor say u.s. att...
2      sun 16 apr 2017 death toll aleppo bomb attack ...
3      wed 19 apr 2017 aleppo bomb blast kill six syr...
4      sun 10 jul 2016 29 syria rebel dead fight key ...
                             ...
799    28-08-2016 turkish bombard kill 20 civilian sy...
800    17-08-2016 martyr terrorist shell aleppo salah...
801    03-08-2016 chemic attack kill five syrian alep...
802    01-08-2016 5 kill russian militari chopper sho...
803    april 6 2017 syrian armi kill 48 isil terroris...
Name: content, Length: 804, dtype: object

In [33]:
# Separting data and label
X = news_dataset['content'].values
Y = news_dataset['labels'].values

In [34]:
print(X)
print(Y)

['wed 05 apr 2017 syria attack symptom consist nerv agent use who. victim suspect chemic attack syria appear show symptom consist reaction nerv agent world health organ said wednesday. "some case appear show addit sign consist exposur organophosphoru chemic categori chemic includ nerv agents" said statement put death toll least 70. unit state said death caus sarin nerv ga drop syrian aircraft. russia said believ poison ga leak rebel chemic weapon depot struck syrian bombs. sarin organophosporu compound nerv agent. chlorin mustard ga also believ use past syria not. russian defenc ministri spokesman say agent use attack said rebel use chemic weapon aleppo last year. said like kind chemic use attack suffer appar extern injuri die rapid onset similar symptom includ acut respiratori distress. said expert turkey give guidanc overwhelm health worker idlib diagnosi treatment patient medicin atropin antidot type chemic exposur steroid symptomat treatment sent. u.n. commiss inquiri human right syria previous said forc loyal syrian presid bashar al-assad use lethal chlorin ga multipl occasions. hundr civilian die sarin ga attack ghouta outskirt damascu august 2013. assad govern alway deni respons attack. syria agre destroy chemic weapon 2013 deal broker moscow washington. russia syrian alli china repeatedli veto unit nation move sanction assad refer situat syria intern crimin court. "these type weapon ban intern law repres intoler barbarism" peter salama execut director health emerg programm said statement. - reuter idlib'
 'fri 07 apr 2017 0914 hom governor say u.s. attack caus death doesnt see big human losses. u.s. missil strike airbas near syrian citi hom friday caus death believ result "big human casualties" hom governor talal barazi said. barazi said attack serv interest "arm terrorist groups" includ islam state ad target airbas provid air support armi oper islam state east palmyra. barazi speak seri phone interview media friday. confirm death airbas phone interview lebanes tv station al-mayadeen. "i believ - god will - human casualti big materi damage. hope mani victim martyrs" told reuter telephone. speak dawn said rescu fire-fight oper go two hour base. said attack form "support arm terrorist group attempt weaken capabl syrian arab armi combat terrorism". speak syrian state tv barazi said "the syrian leadership syrian polici change. "thi target first dont believ last" added. separ comment al-mayadeen said "the war terror continue." u.s. presid donald trump said order missil strike airfield deadli chemic weapon attack launch week declar act america "nation secur interest" syrian presid bashar al-assad. u.s. offici said militari fire dozen cruis missil base respons suspect ga attack rebel-held area washington blame assad forces. syrian govern strongli deni responsibility. u.s. strike "target militari posit syria hom specifically" order publicli "serv goal terror syria goal israel long run" barazi ad interview state tv.-reuter hom'
 'sun 16 apr 2017 death toll aleppo bomb attack least 112. death toll bomb blast crowd syrian bu convoy outsid aleppo reach least 112 peopl syrian observatori human right monitor group said sunday. syrian rescu worker civil defenc said cart away least 100 bodi site saturday blast hit buse carri shiit resid wait cross rebel govern territori evacu deal war sides. british-bas observatori said number expect rise. kill mostli resid villag al-foua kefraya idlib provinc includ rebel fighter guard convoy observatori said. immedi claim respons attack pro-damascu media said carri suicid car bomber. convoy carri least 5000 peopl includ civilian sever hundr pro-govern fighter grant safe passag two shiit villag besieg rebels. evacu deal 2000 peopl includ rebel fighter grant safe passag madaya town near damascu besieg govern forc allies. convoy wait bu garag government-held area aleppo outskirt mile attack took place. madaya evacue said heard blast. --reuter aleppo'
 'wed 19 apr 2017 aleppo bomb blast kill six syrian state tv. bomb blast kill six peopl injur 32 salah al-din district aleppo syrian state televis report wednesday without give details. salah al-din locat west aleppo old citi district part last rebel enclav taken syrian armi advanc december. --reuter aleppo'
 'sun 10 jul 2016 29 syria rebel dead fight key aleppo road. least 29 syrian rebel kill clash regim troop overnight fail bid reopen opposit key suppli rout aleppo citi monitor said sunday. fighter faylaq al-sham islamist faction al-qaeda affili al-nusra front kill tri reopen castello road regim forc effect sever thursday syrian observatori human right monitor said.--afp aleppo'
 'tue 05 jul 2016 suicid bomb kill least 16 northeast syria. suicid bomb blast kill least 16 peopl mostli kurdish-control citi hasaka northeastern syria tuesday monitor group syrian observatori human right said. attack deton explos bakery. british-bas observatori said sever peopl wound death toll like rise number seriou injuries. immedi claim respons bombing. islam state target area hasaka provinc past includ anoth citi qamishli. bomb attack hasaka citi rarer recent months. kurdish ypg militia control hasaka provinc captur larg area territori islam state northeastern syria last year involv u.s.-back offens jihadist west near turkish border. --reuter hasakeh'
 'sun 05 jul 2015 22 dead heavi u.s. raid syria stronghold. six civilian includ child among least 22 peopl kill u.s. air strike islam state group de facto syrian capit saturday sunday monitor said. rest dead raid citi raqa fighter syrian observatori human right said. dozen peopl also wounded. u.s.-l coalit launch air war syria last septemb said carri "significant" air strike raqa. "the signific air strike tonight execut deni daesh (is) abil move militari capabl throughout syria iraq" spokesman lieuten colonel thoma gilleran said. "thi one largest deliber engag conduct date syria debilit effect daesh abil move raqa." coalit forc "success engag multipl targets" throughout raqa statement said destroy structur transit routes. strike "have sever constrict terrorist freedom movement" added. washington lead coalit fight syria iraq extremist group proclaim islam "caliphate" territori control. group emerg syria 2013 control around half countri territori though much land hold unpopul desert. 230000 peopl kill syria sinc conflict began march 2011.-afp raqqa'
 'sun 22 feb 2015 suicid bomber kill 4 assad clan hometown. suicid bomber drive ambul kill four peopl sunday unpreced attack hospit took syria civil war rule assad clan hometown first time monitor group said. attack came syrian observatori human right report troop execut 48 peopl earlier week northern villag among 10 children. "a man drove ambul pack explos park qardaha hospital. anoth man vehicl unclear whether accomplic hostage. four peopl kill attack" said observatori director rami abdel rahman. earlier state televis report blast specifi natur attack. attack first explos hit heart western town sinc outbreak syria civil war 2011 kill nurs hospit employe two soldier said observatori director abdel rahman. outskirt qardaha previous come rocket fire latakia provinc - town locat - seen sever round heavi fighting. mausoleum contain grave presid bashar assad father predecessor hafez brother bassil locat qardaha. clan rule syria iron fist 40 years. syria war began march 2011 pro-democraci revolt seek assad ouster. morph conflict regim unleash brutal crackdown dissent. - troop kill 10 children - meanwhil observatori said 10 children 13 rebel among 48 peopl execut govern forc northern villag rityan earlier week. kill took place troop enter town tuesday offens aim cut rebel suppli line turkish border. abdel rahman said dead six families. "there resist except one hous rebel open fire troop execut along family." brief seizur rityan part abort armi offens week encircl rebel-held east aleppo reliev two besieg shiit villag north. friday one villag taken govern forc recaptur rebel includ fighter al-qaeda affili al-nusra front. heavi fight claim live 129 loyalist 116 rebel includ al-nusra command accord observatori toll. - air raid kill thousand - ground offens fail warplan kept pound rebel area aleppo citi part country. saturday two women two children among eight peopl kill barrel bomb hit build opposition-held area aleppo citi syria commerci capital. six peopl also report kill rebel shell regime-held area city. air forc also kill least 10 peopl rebel area east damascu saturday observatori said. accord group latest 7000 peopl kill across syria sinc un secur council pass resolut last year order end sieg indiscrimin use weapon popul areas. observatori "ha document kill 5812 civilian includ 1733 children 969 women 3110 men barrel bomb (other) air raids" past year. meanwhil rebel fire regime-held area kill 1102 peopl said observatori ad 234 children. 313 peopl die area armi sieg past year result food medic shortag despit fact resolut also order lift sieges.-afp lattakia'
 'sun 01 feb 2015 explos rock town damascu . explos insid bu kill six peopl injur anoth ten town damascu accord preliminari report sunday. syria govern run tv said explos took place al kalassa region syrian capit 19 peopl injur unspecifi number other killed. damascu'
 'sat 24 aug 2013 damascu explos due rocket bomb . blast heard saturday even area burj rouss qsaa syrian capit damascu due rocket bomb car explos nna correspond reported. rocket bomb pack heavi explos materi led kill one person injuri 40 others; addit caus huge materi damag within area explos nna correspond ad quot syrian nation television. damascu'
 '12 februari 2015 casualti mount eastern ghouta citi regim continu assault tenth day row. 120 peopl kill troop alli syrian regim step attack syria eastern ghouta governor focus citi douma around 10km northeast damascus. regim aircraft drop 1000 bomb citi least 150 airstrik past ten day accord analysts. "rescu team volunt continu search survivor bodi rubbl amid mass destruct neighbourhoods" osama said douma-bas media activist told al-arabi al-jadeed. least 400 peopl - mainli women children - injur bomb campaign 500 residenti build destroy accord citi monitor document office. retali administr presid bashar al-assad said attack ramp zahran alloush leader armi islam - merg collect rebel opposit group - declar damascu militari zone [ar] shot hundr missil capital. rescu team volunt continu search survivor bodies. - osama said media activist latest escal also attempt regim forc break eastern ghouta control armi islam. douma-bas activist drawn world attent tragedi use hashtag doumaextermin arab equivalent. pictur video citi post use hashtag shown dozen sever injur children receiv treatment makeshift hospit well injur civilian dead bodi pull rubble. "pictur douma high civilian bodi count show regim target residenti area militari sites" said hisham marwah syrian nation coalit (snc) vice-president. regim use polici collect punish mani part syria sinc upris began added. marwah call intern commun put pressur assad regim stop massacr immediately. "the intern allianc add assad posit locat target attack islam state group syria" added. locat target assad troop week eastern ghouta includ town misraba ayn tarma arbin kafr batna al-wafideen refuge camp. articl edit translat arab edition. also damascu'
 '12 februari 2015 free syrian armi nusra front fighter push town deir al-ada surround area rebel claim iranian-back lebanes group want set perman base. hizballah fighter back syrian iranian forc push nusra front town deir al-ada report say major offens daraa governorate. london-bas syrian observatori human right said deir al-ada taken tuesday two day fierc fight regim element rebel includ member nusra al-qaeda affili syria fighter free syrian army. offens part oper launch sunday seiz area intersect point three syrian governor rif dimashq daraa quneitra near disput golan heights. observatori group said 20 opposit fighter kill fight includ hizballah ambush near deir al-adas. group director rami abdulrahman told afp news agenc hizballah lead attack deir al-ada surround hills. al-arabi al-jade cannot independ verifi reports. restor secur offici syrian news agenc sana quot militari sourc wednesday say armi abl "restor security" sanei tal al-hawa tal-ar southwestern countrysid damascu tal meri west damascu al-danaji tal antar near deir al-adas. opposit local coordin committe deir al-ada said heavi shell forc free syrian armi town "in rang firepower". ayman al-aasmi member fsa southern front command claim hizballah tri set perman base north daraa link posit southern lebanon hill mount hermon. "the issu retak town hills" said. "hizballah push larg forc battl mostli made lebanes iraqi militia light regim forc collaps daraa governor result loss battl opposit forc defect redeploy hot spot governorates." articl edit translat origin arabic. damascu'
 '23 februari 2015 sawaiq al-rahman brigad announc kill sever nusra front fighter clash opposit group continue. tag syria free syrian armi opposit group sawaiq al-rahman brigad al-nusra front idlib sawaiq al-rahman brigad announc monday kill six nusra front fighter injur sever other countrysid south idlib northwest syria. brigad syrian opposit faction affili free syrian armi (fsa). "the oper carri respons al-nusra attack town amiriyah set fire sever hous - includ one belong mithqal al-abdallah former syrian revolutionari front (srf) commander" sawaiq al-rahman brigad stated. al-nusra mani enemies. also mani hostag includ son. - col haitham afisi former fsa deputi chief staff brigad also recent kill abu hassan al-nusra leader town salqin countrysid around idlib. hang "violat commit al-nusra town civilians" accord statement issu brigade. fsa special forc seventh divis also issu statement give al-nusra 48 hour releas took hostag nearli week ago storm headquart town larouz. taken includ divis command sever fighters. statement also call al-nusra return possess taken abid "the law god" prevent bloodshed. former fsa deputi chief staff colonel haitham afisi said past eight month al-nusra also attack fighter group includ fsa srf hazzm maarat al-noman martyr brigad idlib martyr brigad led mithal al-abdallah yusuf al-hassan. "al-nusra mani enemies. also mani hostag includ son brigad command detain four months" afisi told al-arabi al-jadeed. colonel said group lost popular support becom target attack like unit it. nusra front al-qaeda franchis oper syria lebanon aim overthrow regim presid assad syria. group design "a terrorist organisation" mani western governments. earli novemb 2014 al-nusra start expand countrysid around idlib clash opposit faction particularli srf. al-nusra sinc seiz control countrysid south idlib provinci capital. articl edit translat arab edition. idlib'
 '6 juli 2015 call islam state group post onlin new disturb video show murder two syrian activist confess spying. tag syria islam state activist murder video palmyra islam state group releas new video purport show kill two syrian activist milit stronghold raqqa allegedli spi extremists. kill hundr peopl sinc declar islam caliph june last year citi raqqa de facto capital. video post monday is-link facebook page show two young men orang jumpsuit say film photograph is-held area syria sent footag person abroad. identifi 21-year-old faysal hussein habibi 20-year-old bishr abdul-azim. tie tree mask gunmen shoot head close range. follow releas video post onlin n 4 juli purportedli show islam state fighter kill 25 syrian soldier histor town palmyra central syria. score syrian troop state employe kill day palmyra fell is. video show soldier taken pickup truck town notori tadmur prison amphitheatre. theatr shot dead young member arm pistols. hundr peopl seen watch killings. video indic kill took place. britain-bas syrian observatori human right said shoot took place 27 may. report may score syrian troop state employe murder day town fell 22 may 2015. palmyra unesco world heritag site famou 2000-year-old roman colonnad ruin priceless artifacts. captur palmyra rais concern milit might tri destroy one middl east spectacular archaeolog site well-preserv roman-era citi town edg destroy pre-islam ancient monument elsewher syria iraq. 2 juli said milit destroy six archaeolog piec palmyra confisc smuggler. shoot video took place insid archaeolog site troop bruis blood face appar result beaten made kneel front giant black flag shot back heads. raqqa'
 '7 juli 2015 suicid bomber al-qaeda syrian affili al-nusra front kill 25 soldier fighter loyal assad regim government-held western aleppo monday monitor group said tag nusra front al-qaeda aleppo syria assad extrem war. suicid bomber syria al qaeda offshoot nusra front blew syrian armi outpost contest neighborhood divid northern citi aleppo kill least 25 soldier alli militia injur score monitor said. uk base syrian observatori human right track violenc across countri said explos blast heard across citi sever islamist-l group recent launch offens control remain western part citi govern hands. rebel websit said heavi bombard rebel-held portion jamiyat al zahra district rebel gain ground brought closer heart govern control part citi 2011 civil war countri main industri commerci hub. rami abdul rahman head monitor group said syrian armi respond heavi firepow includ aerial bombard attempt stem offensive. al qaeda-link insurg post social media imag fighter nusra front head toward district syrian armi repeatedli said recent day fallen insurg hands. syrian televis said syrian armi foil attempt extremist deton explosive-laden truck head toward jamiyat al zahra deton reach target. aleppo'

In [35]:
# convert the text data into meaningful numbers so computer can underdstand
# use the vectorization function

vectorizer = TfidfVectorizer()
vectorizer.fit(X)

X = vectorizer.transform(X)

In [42]:
print(Y)

[0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 0 0 0 1 0 1 0 0
 1 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 0 0 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 0 0
 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 0
 1 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 1 0 0 0 1 1 0 1 0 1
 0 0 0 0 0 1 0 0 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1
 0 1 1 0 0 1 1 1 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0
 1 0 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 1 0 0 0 0 1 1
 0 1 1 1 0 0 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1
 1 0 1 0 1 1 0 0 0 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1
 1 1 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 1 0
 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 1 1 1 0
 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0
 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 1
 1 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 0 1 1 0 1
 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 1 0 0 0
 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 1 1 0 0 0 1 1
 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 1 1
 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 0
 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0
 0 1 1 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1]

In [43]:
# split data into training and test data
X_train, X_test ,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2 , stratify = Y,random_state=2)

In [39]:
# Training the model : logistic Regression Model
model = LogisticRegression()

In [44]:
model.fit(X_train, Y_train)

LogisticRegression()

In [45]:
# Evaluation of model
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [48]:
print('Accuracy score of training data is : ',training_data_accuracy)

Accuracy score of training data is :  0.8880248833592534

In [49]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction , Y_test)

In [50]:
print('Accuracy score of test data is : ',test_data_accuracy)

Accuracy score of test data is :  0.5341614906832298

In [53]:
# Making a predictive system
X_new = X_test[0]
prediction = model.predict(X_new)
if prediction == 0:
  print('Real news')
else:
  print('Fake news')

Real news

In [54]:
print(Y_test[0])

0